# Generated by Django 3.1.4 on 2020-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('rpassword', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=10)),
            ],
        ),
    ]
