# Generated by Django 3.1.4 on 2020-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rpassword',
        ),
        migrations.AddField(
            model_name='reservation',
            name='to_agenda',
            field=models.BooleanField(default=False),
        ),
    ]
