# Generated by Django 3.1.4 on 2020-12-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_auto_20201204_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='delete',
            new_name='dele',
        ),
    ]
